#!/bin/sh
exec tail -n +3 $0
# This file provides an easy way to add custom menu entries.  Simply type the
# menu entries you want to add after this comment.  Be careful not to change
# the 'exec tail' line above.
menuentry 'Windows 8' --class windows --class os $menuentry_id_option 'osprober-efi-0005-6298' {
	insmod part_gpt
	insmod fat
	set root='hd1,gpt1'
	if [ x$feature_platform_search_hint = xy ]; then
	  search --no-floppy --fs-uuid --set=root --hint-bios=hd1,gpt1 --hint-efi=hd1,gpt1 --hint-baremetal=ahci1,gpt1  0005-6298
	else
	  search --no-floppy --fs-uuid --set=root 0005-6298
	fi
	echo '启动中...'
	chainloader /EFI/MSStart/bootmgfw.efi
	echo '马上就好...'
}
